print("=== My Calculator ===")
print("By Nkhensani - Future IS Student")
name = input("What is your name? ")
print(f"Hi {name}! Let's calculate.")
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print(f"\nResults for {num1} and {num2}:")
print(f"Add: {num1 + num2}")
print(f"Minus: {num1 - num2}")
print(f"Times: {num1 * num2}")
print(f"Divide:{num1/num2}")
print("Thanks for using my app!") 
